### ISSUE TITLE
Advanced Settings activation always sets language to english

### ISSUE THREAD

**Issue by xy124** [Amos2016GroupOne/amos-ss16-proj1#124]
When changing language then leaving the app and entering it again it changes the language always to English when activating advanced settings as this is the first entry in the list. Probably there is the same issue with volume profiles as they use a simular Mechanism.

Would be cool if sb could write an e2e test to reproduce this bug and then solve it!

**Comment by Aedge90** [comment]
I just tested it on android 6 and I cant reproduce it. I leave or kill the app, then I reenter and click on show advanced settings and it still has the language set that was set before

**Comment by Blackclaws** [comment]
Can not reproduce this bug either

**Comment by domkrel** [comment]
Never happened for me too. No clue how it even could happen.
It is just a ng-if in html to show or hide the setting div

**Comment by xy124** [comment]
Ok I'm gonna close it. Seems as if I had an old version for my test.
