### ISSUE TITLE
If arabic is set on start of the app the volume slider is not RTL

### ISSUE THREAD

**Issue by Aedge90** [Amos2016GroupOne/amos-ss16-proj1#127]
1. Set arabic as language (now the volume slider is RTL as it should be)
2. close the app
3. restart the app
4. Go to settings tab

--> the volume slider is now LTR again, which it should not be, but the volume icons are correct

**Comment by xy124** [comment]
Has this sth todo with the advanced settings button maybe?

**Comment by Aedge90** [comment]
I already fixed it. It was just because I switched to RTL only if the language was changed to arabic. But not if the language was already arbic in the first place.

**Comment by xy124** [comment]
:+1:
