### ISSUE TITLE
Remove Splash Screen upon App start

### ISSUE THREAD

**Issue by horenzloerner** [Amos2016GroupOne/amos-ss16-proj1#35]
Splash screen during the app startup is removed.

**Comment by xy124** [comment]
does that really make sense? or do we just need another splash screen?
At least on blackberry it feels slow without the splash screen!

**Comment by Aedge90** [comment]
why does it feel slow then?

**Comment by xy124** [comment]
because on my bb  I can see how the angular scripts and so on construct the apps controls... That was hidden by the splash screen before...

**Comment by Aedge90** [comment]
Ah ok for me the app starts slightly faster without the splashscreen (about 1 second) and I dont see any construction going on

**Comment by xy124** [comment]
Ok so lets keep it without splash screen as BB is no officially supported platform ;)
