### ISSUE TITLE
Profile settings not marked after restarting app

### ISSUE THREAD

**Issue by Aedge90** [Amos2016GroupOne/amos-ss16-proj1#43]
when I choose a volume profile, it is marked and the volume is set
when I restart the app it is not marked anymore.
It would probably be nice if it was.

**Comment by xy124** [comment]
Yep I know. I will investigate in this. It seems to be somehow buggy in Angular/ionic as the correct volume level is selected but even if the correct data model was connected with the radio select of volume profiles restarting the app does not restore the tick there  :/ ... But I will see..

**Comment by xy124** [comment]
Ah I saw the mistake:

``` js
var a ={a:1}, b={a:1}, c=a;
>a==c
true
// but: 
>a==b
false
```

So object compare was the problem. 
Converting to JSON did the trick :)
