### ISSUE TITLE
ScanDurationSlider - wrong steps

### ISSUE THREAD

**Issue by domkrel** [Amos2016GroupOne/amos-ss16-proj1#63]
The ScanDurationSlider has following problems:
- max 31 instead of 60
- steps 1, 6, 11, 16 instead of 1, 5, 10, 15

Solution:
- Set max to 60
- Change the step dynamic via js to get the 1, 5, 10, 15, ... done

**Comment by Aedge90** [comment]
In my new feature I use a new slider. I set the slider min max to go from 1 to 60. The steps are also correct. So if we merge my slider this issue will be solved

**Comment by domkrel** [comment]
Do you have a step of 5 AND you get 1, 5, 10?
That would be a cool slider. I thought that we would need a dirty workaround for it
Will have a look on your code now.

**Comment by Aedge90** [comment]
With that slider it is actually possible without a workaround. The thing is that the range of the slider is from 0 to 60 with step size 5. But in addition you can specify a minimal value that the user can set, which is 1 in our case. So the slider does not reach 0 but stops at 1

**Comment by domkrel** [comment]
I just tested it. Really good. So I think we can close this issue again.
