### ISSUE TITLE
App is freezing

### ISSUE THREAD

**Issue by xy124** [Amos2016GroupOne/amos-ss16-proj1#76]
## How to reproduce:
- seems to occur randomly

--> Test with logs and debugger enabled :zap: :zap: :mag:

**Comment by xy124** [comment]
When in inspect we got the following logs:

the second occured after hitting pause.

[amos-ss16-proj1.zip](https://github.com/Amos2016GroupOne/amos-ss16-proj1/files/328000/amos-ss16-proj1.zip)

**Comment by Aedge90** [comment]
So the digest errors are only related to pausing and not the freeze?

**Comment by xy124** [comment]
I guess.oO
Maybe you can test a bit the graph in the debugger?

**Comment by Blackclaws** [comment]
See also the fix-freezes branch

**Comment by Aedge90** [comment]
I can not reproduce the freeze. I did some stress testing with chrome inspect but no chance to freeze the app. Maybe it has something to do with the sensor tags or it is really already fixed

**Comment by Blackclaws** [comment]
No longer any freezes even during rapid stress testing
