### ISSUE TITLE
Graph Controller Logs

### ISSUE THREAD

**Issue by Aedge90** [Amos2016GroupOne/amos-ss16-proj1#79]
In the Graph Controller. There are three logs:
Log.add("Mousemove: " + JSON.stringify($event));
Log.add("Stop Drag: " + JSON.stringify($event));
Log.add("Start Drag: " + JSON.stringify($event));

They spam the console with:
06-13 15:17:13.725: I/chromium(29886): [INFO:CONSOLE(26771)] "TypeError: Converting circular structure to JSON

Should we just remove them?

**Comment by xy124** [comment]
I'd say yes, remove them!

**Comment by Blackclaws** [comment]
Its interesting that they are circular for you. They aren't circular for me. But we can remove them anyway I just used them while developing.

**Comment by xy124** [comment]
@Blackclaws were you testing in browser(what I did) or on a phone?
