### ISSUE TITLE
ionic serve not working anymore

### ISSUE THREAD

**Issue by Aedge90** [Amos2016GroupOne/amos-ss16-proj1#93]
when I run "ionic serve" I get the following output in the browser:

```
14:07:43.947 Error: openDatabase is not defined
initDB@http://localhost:8100/js/controllers/tag.js:68:13
```

**Comment by domkrel** [comment]
The cordovaPlugin is not available if you make ionic serve.
But i already built something to use another database-engine instead. Obviously it does not work.
Will have a look on it.

**Comment by Aedge90** [comment]
Ok @xy124 already made a mock object for $rootScope.db if running in browser. So I thought maybe also a mock object would do. But its unnecessary if we use another database engine probably
