### ISSUE TITLE
DB-Measure does not deactivate when permissions are not given

### ISSUE THREAD

**Issue by xy124** [Amos2016GroupOne/amos-ss16-proj1#96]
When activating the DBMeter on a phone with volume measurement disabled a Popup is shown asking for granting the needed permissions. If the user declines, the toggle is anyway switched.

The proper way would be to first check for permissions and only move toggle if those were given.

**Comment by Blackclaws** [comment]
Yeah so this is actually a bit stupid. If you look into the plugin code itself I don't think there is a specific callback for when that request fails. I'm goign to investiage this further

**Comment by Blackclaws** [comment]
Its actually even more stupid. It tries to request the permission even when just querying whether its listening. Thats why if you deny it permission and then try to turn off the toggle it actually requests multiple times and always returns true....

**Comment by xy124** [comment]
Omg ... thanks Blackclaws for working on this. I was totally knocked out by the tutorial-thing...
